apiVersion: v1
kind: ServiceAccount
metadata:
  name: insurance-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-app
  labels:
    app: insurance-app
    environment: production
    owner: vardaan
spec:
  replicas: 2
  selector:
    matchLabels:
      app: insurance-app
  template:
    metadata:
      labels:
        app: insurance-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8081"
    spec:
      serviceAccountName: insurance-sa
      containers:
        - name: insurance-container
          image: vardaandocker/insurance-tuesday:1.0
          ports:
            - containerPort: 8081
          env:
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx512m"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 5
      # Optional: schedule pods only on specific node group (e.g., with label disktype=ssd)
      # nodeSelector:
      #   disktype: ssd
---
apiVersion: v1
kind: Service
metadata:
  name: insurance-service
  labels:
    app: insurance-app
spec:
  selector:
    app: insurance-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer
