apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insurance-app
  template:
    metadata:
      labels:
        app: insurance-app
    spec:
      containers:
        - name: insurance-container
          image: vardaandocker/insurance-tuesday:1.0
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: insurance-service
spec:
  selector:
    app: insurance-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
