apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-app
  labels:
    app: insurance
    tier: backend
  annotations:
    description: "Deployment for Insurance application running on port 8081"
spec:
  replicas: 2  # Increased replicas for high availability
  selector:
    matchLabels:
      app: insurance
  template:
    metadata:
      labels:
        app: insurance
        tier: backend
      annotations:
        maintainer: "youremail@example.com"
    spec:
      containers:
        - name: insurance-container
          image: vardaandocker/insurance-tuesday:1.0
          ports:
            - containerPort: 8081  # corrected port to match your running service
          env:
            - name: ENVIRONMENT
              value: "production"
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx512m"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: insurance-service
  labels:
    app: insurance
  annotations:
    description: "Service exposing Insurance application using LoadBalancer"
spec:
  selector:
    app: insurance
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081  # corrected target port to match your app's container port
  type: LoadBalancer
